services:
    mongo:
        image: mongo
        # restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
        ports:
            - 27017:27017
        volumes:
            - ./.mongo-data:/data/db
    redis:
        image: redis
        # restart: always
        ports:
            - 6379:6379
        volumes:
            - ./.redis-data:/data
        environment:
            REDIS_USERNAME: root
            REDIS_PASSWORD: password
            REDIS_DISABLE_DEFAULT_USER: "true"
               
